/* 
**  mod_authn_yubikey.c -- Apache sample authn_yubikey module
**  [Autogenerated via ``apxs -n authn_yubikey -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_authn_yubikey.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /authn_yubikey in as follows:
**
**    #   apache2.conf
**    LoadModule authn_yubikey_module modules/mod_authn_yubikey.so
**    <Location /authn_yubikey>
**    SetHandler authn_yubikey
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /authn_yubikey and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/authn_yubikey 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_authn_yubikey.c
*/ 

#include <stdio.h>
#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_log.h"
#include "mod_auth.h"
#include "yubi_zeromq_client.h"

#define SERVER_LINK "tcp://localhost:555"
#define TOKEN_DIR "/var/lib/mod_authn_yubikey"
#define GRACE_TIME (60*10)

static authn_status authn_check_token(request_rec *r, const char *user,
				      const char *token)
{
  int retval;
  char *ip, *token_file_p, *old_token, *old_ip;
  char line[128];
  FILE *token_file;
  int ii, user_length;
  struct stat sb;

  user_length = strlen(user);
  for (ii = 0; ii < user_length; ii++)
    if ((user[ii] == '.' ) || (user[ii] == '/') || (user[ii] == '\\'))
      {
	ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
		      "Invalid character in user '%s'", user);
	return AUTH_DENIED;
      }
  token_file_p = malloc(sizeof(char) * (user_length + strlen(TOKEN_DIR) + 2));
  sprintf(token_file_p, "%s/%s", TOKEN_DIR, user);
  ip = r->connection->remote_ip;
  if (!stat(token_file_p, &sb))
    {
      if ((time(NULL) - GRACE_TIME) > sb.st_mtime)
	goto discard_old_token;
      token_file = fopen(token_file_p, "r");
      fgets(line, 128, token_file);
      fclose(token_file);
      old_token = strtok(line, " ");
      if (old_token == NULL)
	goto discard_old_token;
      old_ip = strtok(NULL, " ");
      if (old_ip == NULL)
	goto  discard_old_token;
      if (strcmp(token, old_token) != 0)
	{
	  ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r, "token mismatch '%s / %s'", token, old_token);
	  goto discard_old_token;
	}
      if (strcmp(ip, old_ip) != 0)
	{
	  ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r, "IP mismatch '%s / %s'", ip, old_ip);
	  goto discard_old_token;
	}
      /*
       * If we are there, the token and IP should match and we should be in the
       * grace time.
       */
      free(token_file_p);
      return AUTH_GRANTED;
    }
 discard_old_token:
  //ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r, "Connection from '%s'", ip);
  retval = ask_server(user, token, SERVER_LINK);
  if (retval == CHK_OK)
    {
      token_file = fopen(token_file_p, "w");
      fprintf(token_file, "%s %s", token, ip);
      fclose(token_file);
      free(token_file_p);
      return AUTH_GRANTED;
    }
  free(token_file_p);
  return AUTH_DENIED;
}


static const authn_provider authn_yubikey_provider = {
    &authn_check_token,
    NULL
};

static void authn_yubikey_register_hooks(apr_pool_t *p)
{
  //ap_hook_handler(authn_yubikey_handler, NULL, NULL, APR_HOOK_MIDDLE);
  ap_register_provider(p, AUTHN_PROVIDER_GROUP, "yubikey", "0",
		       &authn_yubikey_provider);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA authn_yubikey_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    authn_yubikey_register_hooks  /* register hooks                      */
};

